apiVersion: v1
kind: Pod
metadata:
  name: armory-cli
  namespace: jenkins
  containers:
        - command:
            - /bin/sh
            - '-c'
            - pwd; ls; armory deploy start -f deploy.yml -c CLIENT_ID -s SECRET
          image: 'armory/armory-cli:latest'
          name: armory-cli
