apiVersion: v1
kind: Service
metadata:
  labels:
    app: potato-facts
  name: potato-facts-internal
spec:
  ports:
  - name: gate-tcp
    port: 80
    protocol: TCP
    targetPort: 9001
  selector:
    app: potato-facts
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: potato-lies
  name: potato-lies-internal

spec:
  ports:
    - name: gate-tcp
      port: 80
      protocol: TCP
      targetPort: 9001
  selector:
    app: potato-lies












