#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    app: potato-facts
#  name: potato-facts-external
#
#spec:
#  externalTrafficPolicy: Cluster
#  ports:
#  - name: gate-tcp
#    port: 80
#    protocol: TCP
#    targetPort: 9001
#  selector:
#    app: potato-facts
#  type: LoadBalancer
#
#---
apiVersion: v1
kind: Service
metadata:
  name: potato-facts-external #potato-facts-cluster-svc
  labels:
    app: potato-facts-2
  annotations:
    linkerd.io/inject: enabled
spec:
  selector:
    app: potato-facts
  ports:
    - name: http
      port: 80
      targetPort: 9001
      protocol: TCP

#---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    app: potato-lies
#  name: potato-lies-external
#
#spec:
#  externalTrafficPolicy: Cluster
#  ports:
#    - name: gate-tcp
#      port: 80
#      protocol: TCP
#      targetPort: 9001
#  selector:
#    app: potato-lies
#  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: potato-lies-external #potato-lies-cluster-svc
  labels:
    app: potato-lies-2
  annotations:
    linkerd.io/inject: enabled
spec:
  selector:
    app: potato-lies
  ports:
    - name: http
      port: 80
      targetPort: 9001
      protocol: TCP












