---
# Source: remote-network-agent/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: remote-network-agent-service-account
  labels:
    helm.sh/chart: remote-network-agent-2.0.3
    app.kubernetes.io/name: "remote-network-agent"
    app.kubernetes.io/instance: demo-staging-cluster
    app.kubernetes.io/version: "v3.0.31"
    app.kubernetes.io/managed-by: Helm
---
# Source: remote-network-agent/templates/cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rna-demo-staging-cluster-cr
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
# Source: remote-network-agent/templates/cluster-role-binding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rna-demo-staging-cluster-cr-binding
  labels:
    helm.sh/chart: remote-network-agent-2.0.3
    app.kubernetes.io/name: "remote-network-agent"
    app.kubernetes.io/instance: demo-staging-cluster
    app.kubernetes.io/version: "v3.0.31"
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: remote-network-agent-service-account
    namespace: borealis-demo-agent-staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rna-demo-staging-cluster-cr
---
# Source: remote-network-agent/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remote-network-agent-deployment
  labels:
    helm.sh/chart: remote-network-agent-2.0.3
    app.kubernetes.io/name: "remote-network-agent"
    app.kubernetes.io/instance: demo-staging-cluster
    app.kubernetes.io/version: "v3.0.31"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: "remote-network-agent"
      app.kubernetes.io/instance: demo-staging-cluster
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "remote-network-agent"
        app.kubernetes.io/instance: demo-staging-cluster
    spec:
      serviceAccountName: remote-network-agent-service-account
      containers:
        - name: remote-network-agent
          image: "armory/remote-network-agent:v3.0.31"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8080
          startupProbe:
            periodSeconds: 1
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 60
            httpGet:
              path: /health/liveness
              port: 8080
          env:
            - name: APPLICATION_NAME
              value: "rna"
            - name: APPLICATION_ENVIRONMENT
              value: prod
            - name: APPLICATION_VERSION
              value: "v3.0.31"
            - name: LOGGER_TYPE
              value: "console"
            - name: LOGGER_LEVEL
              value: "info"
            - name: DISABLE_COLORS
              value: "false"
            - name: oidc_clientId
              value: "encrypted:k8s!n:rna-client-credentials!k:client-id"
            - name: oidc_clientSecret
              value: "encrypted:k8s!n:rna-client-credentials!k:client-secret"
            - name: agent_identifier
              value: "demo-staging-cluster"
            - name: agent_kubernetesClusterModeEnabled
              value: "true"
