apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: spinnaker

components:
- ../deploy-shared
#- ../deploy-appTargets/potato-facts

resources:
  - baseDeploy.yml

generatorOptions:
  disableNameSuffixHash: true
