name: AutomatedAppDeploy

on:
  repository_dispatch:
    types: AutomatedAppDeploy
jobs:
  build:
    name: automated deploy from main
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout code
        uses: actions/checkout@v2 
      - name: Deployment
        uses: armory/cli-deploy-action@main
        with:
          clientId: "${{ secrets.CDAAS_CLIENT_ID }}"  # "61ihoLa6dkk5SRwAy232H0TJk1xTBbK6"
          clientSecret:  "${{ secrets.CDAAS_CLIENT_SECRET }}" #Client secret that you created in the Armory Cloud Console that has been encrypted with GitHub's encrypted secrets.
          path-to-file: "/deploy-automated-2-env.yml" # Path to the deployment file. For more information, see the Create a deployment file section.
          applicationName: "potato-facts" 
