name: Deploy my latest version

on: workflow_dispatch  

jobs:
  build:
    name: deploy from main
    runs-on: ubuntu-latest
    steps:
      - name: installHelm
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          helm: '3.9.2'
          kustomize: '4.5.7'  
      - name: Checkout code
        uses: actions/checkout@v2 
      - name: buildLocust
        run: kustomize build --enable-helm thirdParty/locust > thirdParty/locust/generatedManifest.yml
      - name: Deployment
        uses: armory/cli-deploy-action@main
        with:
          clientId: "${{ secrets.CDAAS_CLIENT_ID }}"  # "61ihoLa6dkk5SRwAy232H0TJk1xTBbK6"
          clientSecret:  "${{ secrets.CDAAS_CLIENT_SECRET }}" #Client secret that you created in the Armory Cloud Console that has been encrypted with GitHub's encrypted secrets.
          path-to-file: "/deploy-locust.yml" # Path to the deployment file. For more information, see the Create a deployment file section.
          applicationName: "potato-facts-locust-demo" # yes?

